### ISSUE TITLE
Cannot find allure commanline

### ISSUE THREAD

**Issue by tir38** [allure-framework/allure-gradle#52]
#### I'm submitting a ... 
  - [X] bug report
  - [ ] feature request
  - [ ] support request => Please do not submit support request here, see note at the top of this template.

#### If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem

1. followed readme to add basic config 
2 `$ ./gradlew app:allureServe`
3. Saw build error

`> Task :app:allureServe
Cannot find allure commanline in /Users/user/project/.allure/allure-2.4.1

**Comment by AnaScarlet** [comment]
I had the same issue. Had to specify the `downloadLink` in the `allure` task for it to work.

**Comment by vinogradoff** [comment]
@tir38 
probably some problems with download of allure cli.
You can run `./gradlew downlodAllure --info` to get detailed info on why it happened.

**Comment by kazurayam** [comment]
I followed the official document for a project that uses Gradle + Junit5 + Allure.

https://docs.qameta.io/allure/#_junit_5

This tells that all I should do is 2 steps:
1. ```$ gradle clean test```
2. ```$ ./gradlew allureServe```

When I did it, I got an error
```
$ ./gradlew allureServe

> Task :allureServe
Cannot find allure commanline in /Users/kazuakiurayama/github/materialstore/.allure/allure-2.15.0
```

I happened to find [this issue](https://github.com/allure-framework/allure-gradle/issues/52), and I did
```
$ ./gradlew downloadAllure
```

Then the error is fixed. I could see the Report.

----

I think that the [official document](https://docs.qameta.io/allure/#_junit_5) should be revised, should mension "./gradlew downloadAllure"; so that the case of `Cannot find allure commandline` is prevented.
